name: GraalVM Native Image builds
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build image multiarch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image MultiArch(amd64/arm64)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            fielcapao/rinha-de-backend-2023-q3-javarocks-native:latest
