name: GraalVM Native Image builds
on:
  push:
    branches: [ main ]
jobs:
  build:
    if: contains(toJson(github), 'build github')
    name: Build image multiarch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '20.0.1'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GraalVM Set
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Gradle build # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        run: ./gradlew nativeCompile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image MultiArch(amd64/arm64)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile-GithubActions
          push: true
          tags: |
            fielcapao/rinha-de-backend-2023-q3-javarocks-native:latest
